config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home'
  get 'admin/bookings', to: 'admin#index'
  
  resources :bookings, except: [:index]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
    include PriceCalculator
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :animal_name, presence: true
    validates :animal_type, presence: true
    validates :hours_requested, presence: true
    validates :service_date, presence: true

    enum animal_type: { dog: 0, cat: 1 }

    def appointment_price
        calculate_appointment_price(self.animal_type.to_sym, self.hours_requested)
    end

    def self.appointments_price_total
        sum = 0
        Booking.all.each do |b|
            sum += b.appointment_price
        end
        sum
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  # GET admin/bookings
  def index
    @price_total = Booking.appointments_price_total
    @bookings = Booking.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to admin_bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:first_name, :last_name, :animal_name, :animal_type, :hours_requested, :service_date)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<div class="flexit-column">
  <p style="color: green"><%= notice %></p>

  <h1 class="flexit-center">Bookings</h1>


  <div class="flexit-center"><%= link_to "New booking", new_booking_path %></div>
  <br />
  <div class="flexit-center"><%= link_to "Home", root_path %></div>
  <br />
  <div class="flexit-center">
    <div id="bookings">
      <table>
        <tr>
          <th><strong>First name:</strong></th>
          <th><strong>Last name:</strong></th>
          <th><strong>Animal name:</strong></th>
          <th><strong>Animal type:</strong></th>
          <th><strong>Hours requested:</strong></th>
          <th><strong>Service date:</strong></th>
          <th><strong>Appt. price:</strong></th>
          <th><strong>View:</strong></th>
        </tr>
        <% @bookings.each do |booking| %>
          <tr>
            <td><%= booking.first_name %></td>
            <td><%= booking.last_name %></td>
            <td><%= booking.animal_name %></td>
            <td><%= booking.animal_type %></td>
            <td><%= booking.hours_requested %></td>
            <td><%= booking.service_date.strftime("%m-%d-%Y %H:%M") %></td>
            <td><%= number_to_currency(booking.appointment_price, :unit => "$")%></td>
            <td><%= link_to "View", booking %></td>
          </tr>
        <% end %>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td><%= number_to_currency(@price_total, :unit => "$") %></td>
          <td></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>First name:</strong>
    <%= booking.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= booking.last_name %>
  </p>

  <p>
    <strong>Animal name:</strong>
    <%= booking.animal_name %>
  </p>

  <p>
    <strong>Animal type:</strong>
    <%= booking.animal_type %>
  </p>

  <p>
    <strong>Hours requested:</strong>
    <%= booking.hours_requested %>
  </p>

  <p>
    <strong>Service date:</strong>
    <%= booking.service_date.strftime("%m-%d-%Y %H:%M") %>
  </p>

</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div style="color: red;">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>
  <br />
  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>
  <br />
  <div>
    <%= form.label :animal_name, style: "display: block" %>
    <%= form.text_field :animal_name %>
  </div>
  <br />
  <div>
    <%= form.label :animal_type, style: "display: block" %>
    <%= form.select :animal_type, Booking.animal_types.keys %>
  </div>
  <br />
  <div>
    <%= form.label :hours_requested, style: "display: block" %>
    <%= form.number_field :hours_requested, :min => 2, :max => 8 %>
  </div>
  <br />
  <div>
    <%= form.label :service_date, style: "display: block" %>
    <%= form.datetime_field :service_date %>
  </div>
  <br />
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking, class: "button" %>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bookings</h1>

<%= link_to "New booking", new_booking_path %>

<div id="bookings">
  <table>
    <tr>
      <th><strong>First name:</strong></th>
      <th><strong>Last name:</strong></th>
      <th><strong>Animal name:</strong></th>
      <th><strong>Animal type:</strong></th>
      <th><strong>Hours requested:</strong></th>
      <th><strong>Service date:</strong></th>
      <th><strong>Appt. price:</strong></th>
      <th><strong>Link:</strong></th>
    </tr>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.first_name %></td>
        <td><%= booking.last_name %></td>
        <td><%= booking.animal_name %></td>
        <td><%= booking.animal_type %></td>
        <td><%= booking.hours_requested %></td>
        <td><%= booking.service_date %></td>
        <td><%= booking.appointment_price%></td>
        <td><%= link_to "Show this booking", booking %></td>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td><%= @bookings.last.appointments_price_total %></td>
      <td></td>
    </tr>
  </table>
</div>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Home", root_path %>
</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="main_padded">
  <h1>Booking <%= @booking.id %></h1>

  <%= render @booking %>
    <br />
    <%= link_to "Home", root_path, class: "button" %> |
    <%= link_to "Edit this booking", edit_booking_path(@booking), class: "button" %> |
  </div>
  <br />
  <%= button_to "Delete", @booking, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetSitters</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="main_margin">
      <div id="main-header_text"><%= link_to "Admin", admin_bookings_url %></div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/home.html.erb
<div class="flexit-column">
    <div class="flexit-center"><h1 class="flexit-center">Pet</h1><h1 class="flexit-center blue">Sitters</h1></div>
    <div class="flexit-center">
        <%= image_tag "pets.jpg", style: "border-radius: 2rem; max-width: 40rem;" %>
    </div>
    <br />
    <br />
    <div class="flexit-center">
        <%= link_to "Create a Booking", new_booking_path %>
    </div>

</div>